# Generated by Django 5.2.1 on 2025-06-01 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vault", "0003_alter_card_set_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="card",
            name="price_last_updated",
            field=models.DateField(blank=True, null=True),
        ),
    ]
