# Generated by Django 5.2.1 on 2025-08-04 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vault", "0004_card_price_last_updated"),
    ]

    operations = [
        migrations.AlterField(
            model_name="card",
            name="set_code",
            field=models.CharField(
                choices=[
                    ("sv01", "Scarlet & Violet Base"),
                    ("sv02", "Paldea Evolved"),
                    ("sv03", "Obsidian Flames"),
                    ("sv03.5", "151"),
                    ("sv04", "Paradox Rift"),
                    ("sv04.5", "Paldean Fates"),
                    ("sv05", "Temporal Forces"),
                    ("sv06", "Twilight Masquerade"),
                    ("sv06.5", "Shrouded Fable"),
                    ("sv07", "Stellar Crown"),
                    ("sv08", "Surging Sparks"),
                    ("sv08.5", "Prismatic Evolutions"),
                    ("sv09", "Journey Together"),
                    ("sv10", "Destined Rivals"),
                    ("sv10.5b", "Black Bolt"),
                    ("sv10.5w", "White Flare"),
                    ("svp", "Scarlet & Violet Promos"),
                    ("swsh12", "Silver Tempest"),
                    ("swsh12.5", "Crown Zenith"),
                ],
                max_length=10,
            ),
        ),
    ]
