# Generated by Django 5.2.1 on 2025-08-10 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vault", "0005_alter_card_set_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="card",
            name="set_code",
            field=models.CharField(
                choices=[
                    ("Scarlet & Violet Base", "Scarlet & Violet Base"),
                    ("Paldea Evolved", "Paldea Evolved"),
                    ("Obsidian Flames", "Obsidian Flames"),
                    ("151", "151"),
                    ("Paradox Rift", "Paradox Rift"),
                    ("Paldean Fates", "Paldean Fates"),
                    ("Temporal Forces", "Temporal Forces"),
                    ("Twilight Masquerade", "Twilight Masquerade"),
                    ("Shrouded Fable", "Shrouded Fable"),
                    ("Stellar Crown", "Stellar Crown"),
                    ("Surging Sparks", "Surging Sparks"),
                    ("Prismatic Evolutions", "Prismatic Evolutions"),
                    ("Journey Together", "Journey Together"),
                    ("Destined Rivals", "Destined Rivals"),
                    ("Black Bolt", "Black Bolt"),
                    ("White Flare", "White Flare"),
                    ("Silver Tempest", "Silver Tempest"),
                    ("Crown Zenith", "Crown Zenith"),
                ],
                max_length=25,
            ),
        ),
    ]
