# Generated by Django 5.2.1 on 2025-09-09 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vault", "0006_alter_card_set_code"),
    ]

    operations = [
        migrations.RenameField(
            model_name="card",
            old_name="name",
            new_name="card_name",
        ),
        migrations.RenameField(
            model_name="card",
            old_name="set_code",
            new_name="set_name",
        ),
    ]
