# Generated by Django 5.2.1 on 2025-12-18 19:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vault", "0007_rename_name_card_card_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PriceSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "as_of_date",
                    models.DateTimeField(default=django.utils.timezone.localdate),
                ),
                ("source", models.CharField(blank=True, default="", max_length=50)),
                (
                    "currency",
                    models.CharField(blank=True, default="USD", max_length=10),
                ),
                (
                    "card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_snapshots",
                        to="vault.card",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["card", "-as_of_date"],
                        name="vault_price_card_id_02b094_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("card", "as_of_date"), name="uniq_card_price_per_day"
                    )
                ],
            },
        ),
    ]
