# Generated by Django 5.2.1 on 2025-12-27 22:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vault", "0008_pricesnapshot"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pricesnapshot",
            name="as_of_date",
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
