# Generated by Django 5.2.1 on 2025-12-30 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vault", "0009_alter_pricesnapshot_as_of_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="card",
            name="card_number",
            field=models.CharField(max_length=3),
        ),
    ]
